apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.2.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: joe.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: VSI is the Schema for the vsis API
      displayName: VSI
      kind: VSI
      name: vsis.cloud.ibm.com
      version: v1
  description: Virtual Server Instance from IBM Cloud
  displayName: vsi
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - cloud virtual server
  links:
  - name: Joe
    url: https://joe.domain
  maturity: alpha
  provider:
    name: Josiah Samuel
    url: https://github.ibm.com/josiah-sams/hack-vpc-operator
  version: 0.0.0
